### PR TITLE
Change to version 9.0

### PR DESCRIPTION
**Pull request by trinhdev**
TrinhDev - I will be responsible for this content

### CODE REVIEW

**Comment by flyinglb** [comment]
When will laravel9 be supported

**Comment by presleyd** [comment]
Would like to see this merged in so we can upgrade to Laravel 9

**Comment by igorgaming** [comment]
@presleyd We cant, see https://github.com/ckfinder/ckfinder-laravel-package/pull/84

**Comment by zaak** [comment]
Hi @trinhdev. Thank you for the PR. Unfortunately, it's not a simple change and requires significant work to be done in CKFinder connector, as L9 uses version 3 of Flysystem, which collides with version 1 used by CKFinder. We have this change on the roadmap.

**Pull request closed without merging**
